// <auto-generated />
using System;
using AiSupportService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiSupportService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiSupportService.Models.ChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("session_id");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_chat_messages_session_id");

                    b.HasIndex("SessionId", "CreatedAt")
                        .HasDatabaseName("idx_chat_messages_session_created");

                    b.ToTable("chat_messages", t =>
                        {
                            t.HasCheckConstraint("ck_chat_messages_role", "role IN ('user', 'assistant', 'system')");
                        });
                });

            modelBuilder.Entity("AiSupportService.Models.ChatSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("ContextJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("context_json");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserProfileId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_chat_sessions_user_id");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("idx_chat_sessions_user_status");

                    b.ToTable("chat_sessions", t =>
                        {
                            t.HasCheckConstraint("ck_chat_sessions_status", "status IN ('ACTIVE', 'CLOSED', 'ESCALATED')");
                        });
                });

            modelBuilder.Entity("AiSupportService.Models.DemandForecast", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ForecastDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("forecast_date");

                    b.Property<string>("ForecastPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("forecast_period");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version");

                    b.Property<int>("PredictedDemand")
                        .HasColumnType("integer")
                        .HasColumnName("predicted_demand");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("product_id");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_demand_forecasts_product_id");

                    b.HasIndex("ProductId", "ForecastDate")
                        .HasDatabaseName("idx_demand_forecasts_product_date");

                    b.HasIndex("ProductId", "ForecastPeriod")
                        .HasDatabaseName("idx_demand_forecasts_product_period");

                    b.ToTable("demand_forecasts", t =>
                        {
                            t.HasCheckConstraint("ck_demand_forecasts_confidence", "confidence_score >= 0 AND confidence_score <= 1");

                            t.HasCheckConstraint("ck_demand_forecasts_predicted_demand", "predicted_demand >= 0");
                        });
                });

            modelBuilder.Entity("AiSupportService.Models.ModelTraining", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("MetricsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics_json");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters_json");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ModelName")
                        .HasDatabaseName("idx_model_trainings_model_name");

                    b.ToTable("model_trainings", t =>
                        {
                            t.HasCheckConstraint("ck_model_trainings_status", "status IN ('PENDING', 'TRAINING', 'COMPLETED', 'FAILED')");
                        });
                });

            modelBuilder.Entity("AiSupportService.Models.OutboxEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aggregate_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic");

                    b.HasKey("Id");

                    b.HasIndex("AggregateType", "AggregateId")
                        .HasDatabaseName("idx_outbox_events_aggregate");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_outbox_events_status_created");

                    b.ToTable("outbox_events", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_events_retry_count", "retry_count >= 0");

                            t.HasCheckConstraint("ck_outbox_events_status", "status IN ('PENDING', 'PUBLISHED', 'FAILED')");
                        });
                });

            modelBuilder.Entity("AiSupportService.Models.Recommendation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsViewed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_viewed");

                    b.Property<string>("ProductIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("product_ids_json");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric")
                        .HasColumnName("score");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_recommendations_expires");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_recommendations_user_id");

                    b.HasIndex("UserId", "Type")
                        .HasDatabaseName("idx_recommendations_user_type");

                    b.ToTable("recommendations", t =>
                        {
                            t.HasCheckConstraint("ck_recommendations_type", "type IN ('PERSONALIZED', 'TRENDING', 'SIMILAR', 'SEASONAL', 'FREQUENTLY_BOUGHT_TOGETHER')");
                        });
                });

            modelBuilder.Entity("AiSupportService.Models.SearchAnalytics", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("ClickedProductIdsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("clicked_product_ids_json");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("query");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("response_time_ms");

                    b.Property<int>("ResultsCount")
                        .HasColumnType("integer")
                        .HasColumnName("results_count");

                    b.Property<string>("SearchType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("search_type");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_search_analytics_created_at");

                    b.HasIndex("Query")
                        .HasDatabaseName("idx_search_analytics_query");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_search_analytics_user_id");

                    b.ToTable("search_analytics", t =>
                        {
                            t.HasCheckConstraint("ck_search_analytics_search_type", "search_type IN ('KEYWORD', 'SEMANTIC', 'HYBRID')");
                        });
                });

            modelBuilder.Entity("AiSupportService.Models.UserProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("BrowsingHistoryJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("browsing_history_json");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("PreferencesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("preferences_json");

                    b.Property<string>("PurchaseHistoryJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("purchase_history_json");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("LastActivityAt")
                        .HasDatabaseName("idx_user_profiles_last_activity");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_user_profiles_user_id");

                    b.ToTable("user_profiles");
                });

            modelBuilder.Entity("AiSupportService.Models.ChatMessage", b =>
                {
                    b.HasOne("AiSupportService.Models.ChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AiSupportService.Models.ChatSession", b =>
                {
                    b.HasOne("AiSupportService.Models.UserProfile", "UserProfile")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("AiSupportService.Models.Recommendation", b =>
                {
                    b.HasOne("AiSupportService.Models.UserProfile", "UserProfile")
                        .WithMany("Recommendations")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("AiSupportService.Models.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AiSupportService.Models.UserProfile", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("Recommendations");
                });
#pragma warning restore 612, 618
        }
    }
}
