<Project Sdk="Aspire.AppHost.Sdk/13.2.2">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <UserSecretsId>c1d87562-fb13-4184-b8bf-4466c22559be</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.2.2" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.2.2" />
    <PackageReference Include="Aspire.Hosting.Kafka" Version="13.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Services\AdminPortal\AdminPortal.csproj" />
    <ProjectReference Include="..\Services\AiSupportService\AiSupportService.csproj" />
    <ProjectReference Include="..\Services\ApiGateway\ApiGateway.csproj" />
    <ProjectReference Include="..\Services\AuthService\AuthService.csproj" />
    <ProjectReference Include="..\Services\CouponService\CouponService.csproj" />
    <ProjectReference Include="..\Services\Frontend\Frontend.csproj" />
    <ProjectReference Include="..\Services\InventoryManagementService\InventoryManagementService.csproj" />
    <ProjectReference Include="..\Services\MailSendService\MailSendService.csproj" />
    <ProjectReference Include="..\Services\McpServer\McpServer.csproj" />
    <ProjectReference Include="..\Services\PaymentCartService\PaymentCartService.csproj" />
    <ProjectReference Include="..\Services\PointService\PointService.csproj" />
    <ProjectReference Include="..\Services\SalesManagementService\SalesManagementService.csproj" />
    <ProjectReference Include="..\Services\UserManagementService\UserManagementService.csproj" />
  </ItemGroup>
</Project>
